SELECT * FROM CUSTOMERS

UPDATE CUSTOMERS
SET NATION=''

UPDATE CUSTOMERS
SET NATION='TR'

--BÝRDEN FAZLA ALANI UPDATE ETMEK ÝÇÝN
UPDATE CUSTOMERS
SET NATION='TR' , AGE=35

UPDATE CUSTOMERS
SET NATION='US' , AGE=45

SELECT DATEDIFF(YEAR,'1980-12-11','2020-01-01')

SELECT DATEDIFF(YEAR,'1980-12-11',GETDATE())
--YAÞ HESAPLAMA
UPDATE CUSTOMERS
SET NATION='TR' , AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())

INSERT INTO CUSTOMERS
(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE)
VALUES ('KÜBRA YÜCE','ÝSTANBUL', '1996-11-17', 'GOP','K','TR','20')

--DELETE KOMUTU
SELECT * FROM CUSTOMERS
--TÜM SATIRLARI SÝLER
DELETE FROM CUSTOMERS

--TRUNCATE KOMUTU : tabloyu ilk oluþturduðumuz haline dönüþtüren komut. içindeki tüm verileri silen komut.
--Delete from'dan farký id'leri ilk haline alýr. Truncate iþlemi daha hýzlýdýr. id 1 den baþlar devam eder delete'de kaldýðý yerden arttýrýr.
 TRUNCATE TABLE CUSTOMERS

 --WHERE ÞARTI : filtreleme amaçlý kullanýlýr.
  SELECT * FROM CUSTOMERS

  SELECT * FROM CUSTOMERS 
  WHERE CUSTOMERNAME='KÜBRA YÜCE'
  --ÝSTANBUL OLANLARI GETÝR.
  SELECT * FROM CUSTOMERS
  WHERE CITY='ÝSTANBUL'

  --ÝSTANBUL OLMAYANLARI GETÝR.
  SELECT * FROM CUSTOMERS
  WHERE CITY<>'ÝSTANBUL'

  --ÝSTANBUL OLMAYANLARI GETÝR
  SELECT * FROM CUSTOMERS
  WHERE NOT CITY='ÝSTANBUL'
  
  SELECT * FROM CUSTOMERS
  WHERE BIRTHDATE>'1990-01-01'

  SELECT * FROM CUSTOMERS
  WHERE BIRTHDATE<'1990-01-01'

  SELECT * FROM CUSTOMERS
  WHERE BIRTHDATE >='1980-12-11'

  
  SELECT * FROM CUSTOMERS
  WHERE BIRTHDATE <='1996-11-17'

    
  SELECT * FROM CUSTOMERS
  WHERE BIRTHDATE BETWEEN '1980-12-11' AND '1997-11-17'

  SELECT * FROM CUSTOMERS
  WHERE AGE BETWEEN 20 AND 50

  --ÝSMÝ ÖMER ÝLE BAÞLAYAN
  SELECT * FROM CUSTOMERS
  WHERE CUSTOMERNAME LIKE 'ÖMER%'

  --ÝSMÝNDE AL GEÇENLER:
  SELECT * FROM CUSTOMERS
  WHERE CUSTOMERNAME LIKE '%AL%'

    --ÝSMÝ ÖMER ÝLE BAÞLAMAYANLAR:
  SELECT * FROM CUSTOMERS
  WHERE CUSTOMERNAME NOT LIKE 'ÖMER%'
    
  SELECT * FROM CUSTOMERS
  WHERE CITY IN ('BURSA')

  SELECT * FROM CUSTOMERS
  WHERE CITY IN ('BURSA','ÝSTANBUL')

  --CÝNSÝYET YAZILIMLARINI GÜNCELLEME
  UPDATE CUSTOMERS SET GENDER='ERKEK' WHERE GENDER='E'

  UPDATE CUSTOMERS SET GENDER='KADIN' WHERE GENDER='K'

  --ID SEÇEREK LÝSTELEME.
  SELECT * FROM CUSTOMERS WHERE ID=4
  --DELETE ÝÞLEMÝ ÝÇÝN SEÇÝLEN ID'YE GÖRE.
  DELETE  FROM CUSTOMERS WHERE ID=4

  --AND OPERATÖRÜ
  SELECT * FROM CUSTOMERS
  WHERE CITY='ÝSTANBUL' AND DISTRICT='GOP' 

  SELECT * FROM CUSTOMERS
  WHERE GENDER='ERKEK' AND DISTRICT='ÜSKÜDAR' 

  --OR OPERATÖRÜ
  SELECT * FROM CUSTOMERS
  WHERE GENDER='ERKEK' OR DISTRICT='GOP' 

  SELECT * FROM CUSTOMERS
  WHERE GENDER='ERKEK' OR DISTRICT='GOP' OR CITY='BURSA'

  --DISTINCT KOMUTU : tekrar eden komutlarý tek hale getirmesi.10 ürün satýþý olmuþ ve ürün alan müþteri ayný kiþi se bu kullanýlýr.
 -- kaç ilçe var diye sorulunca:
 SELECT DISTINCT CITY ,DISTRICT FROM CUSTOMERS
 WHERE CITY='ÝSTANBUL'

 SELECT DISTINCT GENDER FROM CUSTOMERS
 WHERE CITY='ÝSTANBUL'

 --ORDER BY KOMUTU : sýralama iþlemi için.
 --ÝSÝMLERÝ (A-Z) SIRALI ÞEKÝLDE GETÝRÝR
 SELECT *FROM CUSTOMERS
 ORDER BY CUSTOMERNAME


 SELECT *FROM CUSTOMERS
 ORDER BY CUSTOMERNAME ASC

  --ÝSÝMLERÝ (Z-A) SIRALI ÞEKÝLDE GETÝRÝR
 SELECT *FROM CUSTOMERS
 ORDER BY CUSTOMERNAME DESC

 --ÝKÝ KOLON ISRALAMA
 SELECT *FROM CUSTOMERS
 ORDER BY CITY,CUSTOMERNAME

  SELECT *FROM CUSTOMERS
 ORDER BY CITY ASC,CUSTOMERNAME DESC

 -- KOLON NUMARASI VEREREK DE SIRALAMA SAÐLANABÝLÝR.
	 SELECT *FROM CUSTOMERS
	 ORDER BY 5

--TOP KOMUTU: veri setinin tamamý yerine bir kýsmýný görmemizi saðlayan komut.
	SELECT TOP 2 * FROM CUSTOMERS ORDER BY CUSTOMERNAME

	SELECT TOP 10 PERCENT  * FROM CUSTOMERS ORDER BY CUSTOMERNAME
